# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censustest', '0001_add_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('response_count', models.IntegerField()),
                ('response_percent', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='multiple_valid_choices',
            new_name='select_multiple',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censustest.Question'),
        ),
    ]
