# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def add_topics(apps, schema_editor):
	Question = apps.get_model("censustest", "Question")
	Topic = apps.get_model("censustest", "Topic")
	topics = []
	for t in Question.objects.distinct('topic').values('topic'):
		topics.append(t['topic'])

	for i in range(len(topics)):
		Topic.objects.create(
			text=topics[i],
			sequence_num=i+1
		)

	for q in Question.objects.all():
		topic = Topic.objects.get(text=q.topic)
		q.topic = topic.id
		q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('censustest', '0003_populate_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sequence_num', models.IntegerField()),
            ],
        ),
		migrations.RunPython(add_topics),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censustest.Topic'),
        ),
    ]
