# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censustest', '0004_add_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='sequence_num',
            field=models.IntegerField(unique=True),
        ),
    ]
