# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 16:00
from __future__ import unicode_literals

from django.db import migrations


def scale_percents(apps, schema_editor):
	Choice = apps.get_model("censustest", "Choice")
	for c in Choice.objects.all():
		c.response_percent *= 100
		c.save()

class Migration(migrations.Migration):

	dependencies = [
		('censustest', '0005_make_topic_unique'),
	]

	operations = [
		migrations.RunPython(scale_percents)
	]
