# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models

def update_description_and_footnote(apps, schema_editor):
	Question = apps.get_model("censustest", "Question")

	q = Question.objects.get(title='Non-official languages spoken')
	q.description = 'Non-official languages are other languages excluding English and French.'
	q.footnote = 'The stats for this question do not reflect the entire population of Canada. For example, Spanish is 9.4%. This does not mean that 9.4% of Canadians speak Spanish, it means that of the Canadians that can speak a non-official language, 9.4% of them can speak Spanish.'
	q.save()

	q = Question.objects.get(title='Generation status')
	q.description = 'If you are an immigrant, you are First Generation. If your parents are immigrants, you are Second Generation.'
	q.save()


class Migration(migrations.Migration):

	dependencies = [
		('censustest', '0007_add_alphabetical_choices_field'),
	]

	operations = [
		migrations.AddField(
			model_name='question',
			name='description',
			field=models.CharField(default='', max_length=1000),
		),
		migrations.AddField(
			model_name='question',
			name='footnote',
			field=models.CharField(default='', max_length=1000),
		),
		migrations.RunPython(update_description_and_footnote),
	]
