# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models

def update_alphabetical_choices(apps, schema_editor):
	Question = apps.get_model("censustest", "Question")

	income_question = Question.objects.get(title='Income of individuals in 2010')
	income_question.alphabetical_choices = False
	income_question.save()

	age_question = Question.objects.get(title='Age characteristics')
	age_question.alphabetical_choices = False
	age_question.save()


class Migration(migrations.Migration):

	dependencies = [
		('censustest', '0006_scale_percents'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='question',
			options={'ordering': ['sequence_num']},
		),
		migrations.AlterModelOptions(
			name='topic',
			options={'ordering': ['sequence_num']},
		),
		migrations.AddField(
			model_name='question',
			name='alphabetical_choices',
			field=models.BooleanField(default=True),
		),
		migrations.RunPython(update_alphabetical_choices),
	]
